#!/bin/bash
#
# Setup WrestleBot environment on the server
#
# Run this AFTER deploy.sh to configure the WrestleBot API token
#

set -e

SERVER_USER="root"
SERVER_HOST="wrestlingdb.org"

echo "================================"
echo "WrestleBot Environment Setup"
echo "================================"
echo ""

echo "This script will:"
echo "1. Get the WrestleBot API token from Django"
echo "2. Create /home/wrestlingdb/wrestlebot/.env with the token"
echo ""

read -p "Continue? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

echo ""
echo "Getting API token from server..."

# Get token from server
TOKEN=$(ssh $SERVER_USER@$SERVER_HOST << 'ENDSSH'
cd /home/wrestlingdb
./venv/bin/python -c "
from django.core.management import execute_from_command_line
import sys
import os
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'owdb_django.settings')
import django
django.setup()
from rest_framework.authtoken.models import Token
from django.contrib.auth import get_user_model
User = get_user_model()
try:
    user = User.objects.get(username='wrestlebot')
    token, _ = Token.objects.get_or_create(user=user)
    print(token.key)
except User.DoesNotExist:
    print('USER_NOT_FOUND')
"
ENDSSH
)

if [ "$TOKEN" = "USER_NOT_FOUND" ]; then
    echo "ERROR: WrestleBot user not found!"
    echo "Run: python manage.py setup_wrestlebot_user"
    exit 1
fi

if [ -z "$TOKEN" ]; then
    echo "ERROR: Could not retrieve API token"
    exit 1
fi

echo "Token retrieved: ${TOKEN:0:10}..."
echo ""

echo "Creating .env file on server..."

ssh $SERVER_USER@$SERVER_HOST << ENDSSH
cat > /home/wrestlingdb/wrestlebot/.env << 'EOF'
# WrestleBot Environment Configuration
# Auto-generated by setup_wrestlebot_env.sh

# Django API Configuration
DJANGO_API_URL=https://wrestlingdb.org/api/wrestlebot
WRESTLEBOT_API_TOKEN=$TOKEN

# Ollama AI Configuration
OLLAMA_URL=http://localhost:11434
OLLAMA_MODEL=llama3.2

# Logging
LOG_LEVEL=INFO
LOG_FILE=/var/log/wrestlebot/wrestlebot.log

# Environment
ENVIRONMENT=production
EOF

# Set proper permissions
chmod 600 /home/wrestlingdb/wrestlebot/.env
chown www-data:www-data /home/wrestlingdb/wrestlebot/.env

echo "✓ .env file created at /home/wrestlingdb/wrestlebot/.env"
ENDSSH

echo ""
echo "================================"
echo "Setup Complete!"
echo "================================"
echo ""
echo "Next steps:"
echo "1. Start WrestleBot: ssh $SERVER_USER@$SERVER_HOST 'sudo systemctl start wrestlebot'"
echo "2. Check status:     ssh $SERVER_USER@$SERVER_HOST 'sudo systemctl status wrestlebot'"
echo "3. View logs:        ssh $SERVER_USER@$SERVER_HOST 'sudo journalctl -u wrestlebot -f'"
echo ""
