# Generated by Django 5.2.14 on 2026-05-26 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wrestlebot", "0002_create_models_state_only"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceFetch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("wikipedia", "Wikipedia"),
                            ("cagematch", "Cagematch"),
                            ("profightdb", "ProFightDB"),
                            ("tmdb", "TMDB"),
                            ("wikimedia_commons", "Wikimedia Commons"),
                            ("openlibrary", "Open Library"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("url", models.URLField(max_length=1000)),
                (
                    "entity_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("wrestler", "Wrestler"),
                            ("promotion", "Promotion"),
                            ("event", "Event"),
                            ("match", "Match"),
                            ("title", "Title"),
                            ("venue", "Venue"),
                            ("stable", "Stable"),
                        ],
                        db_index=True,
                        max_length=20,
                        null=True,
                    ),
                ),
                ("entity_id", models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                (
                    "candidate_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Name being looked up (used when entity_id is null)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("http_status", models.IntegerField()),
                (
                    "content_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 of raw_content for change detection",
                        max_length=64,
                    ),
                ),
                (
                    "raw_content",
                    models.TextField(
                        blank=True,
                        help_text="Raw fetched content. Stored verbatim so we can re-extract without re-fetching.",
                    ),
                ),
                ("used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-fetched_at"],
                "indexes": [
                    models.Index(fields=["source", "url"], name="wrestlebot__source_e50d24_idx"),
                    models.Index(
                        fields=["entity_type", "entity_id"], name="wrestlebot__entity__75e792_idx"
                    ),
                    models.Index(fields=["content_hash"], name="wrestlebot__content_464b98_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="GeneratedBio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("wrestler", "Wrestler"),
                            ("promotion", "Promotion"),
                            ("event", "Event"),
                            ("match", "Match"),
                            ("title", "Title"),
                            ("venue", "Venue"),
                            ("stable", "Stable"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("entity_id", models.PositiveIntegerField(db_index=True)),
                ("text", models.TextField()),
                ("model", models.CharField(help_text="e.g., claude-sonnet-4-6", max_length=100)),
                ("generated_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("claims_total", models.IntegerField(default=0)),
                ("claims_verified", models.IntegerField(default=0)),
                (
                    "claims_unsupported",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of claim strings that could not be matched to a source",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending verification"),
                            ("verified", "Verified (all claims supported)"),
                            ("rejected", "Rejected (unsupported claims)"),
                            ("superseded", "Superseded by a newer bio"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("input_tokens", models.IntegerField(blank=True, null=True)),
                ("output_tokens", models.IntegerField(blank=True, null=True)),
                (
                    "source_fetches",
                    models.ManyToManyField(
                        related_name="generated_bios", to="wrestlebot.sourcefetch"
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id", "status"],
                        name="wrestlebot__entity__a78232_idx",
                    ),
                    models.Index(
                        fields=["status", "generated_at"], name="wrestlebot__status_ace006_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FieldProvenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("wrestler", "Wrestler"),
                            ("promotion", "Promotion"),
                            ("event", "Event"),
                            ("match", "Match"),
                            ("title", "Title"),
                            ("venue", "Venue"),
                            ("stable", "Stable"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("entity_id", models.PositiveIntegerField(db_index=True)),
                ("field_name", models.CharField(db_index=True, max_length=100)),
                (
                    "value",
                    models.TextField(help_text="String repr of the value written to the entity"),
                ),
                (
                    "confidence",
                    models.IntegerField(
                        default=100,
                        help_text="0-100. 100 = direct from infobox. Lower if derived/inferred.",
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "source_fetch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="field_provenances",
                        to="wrestlebot.sourcefetch",
                    ),
                ),
            ],
            options={
                "ordering": ["-extracted_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"], name="wrestlebot__entity__d40662_idx"
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id", "field_name"],
                        name="wrestlebot__entity__0e704b_idx",
                    ),
                ],
            },
        ),
    ]
