# Generated by Django 5.2.14 on 2026-05-26 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestlebot', '0003_sourcefetch_generatedbio_fieldprovenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedbio',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1, help_text='1-based: how many bios have been generated for this entity so far'),
        ),
        migrations.AddField(
            model_name='generatedbio',
            name='generation_mode',
            field=models.CharField(choices=[('standard', 'Standard prompt'), ('strict', 'Strict prompt (no inferred combinations)'), ('trim', 'Trimmed: dropped unsupported sentences from a prior attempt')], default='standard', help_text='Which prompt variant produced this bio', max_length=20),
        ),
        migrations.AddField(
            model_name='generatedbio',
            name='parent_bio',
            field=models.ForeignKey(blank=True, help_text='The previous-attempt bio this one is retrying, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='wrestlebot.generatedbio'),
        ),
        migrations.AlterField(
            model_name='generatedbio',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending verification'), ('verified', 'Verified (all claims supported)'), ('rejected', 'Rejected (unsupported claims)'), ('superseded', 'Superseded by a newer bio'), ('permanently_rejected', 'Permanently rejected (max retries exhausted)')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='EntityMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_entity_type', models.CharField(choices=[('wrestler', 'Wrestler'), ('promotion', 'Promotion'), ('event', 'Event'), ('match', 'Match'), ('title', 'Title'), ('venue', 'Venue'), ('stable', 'Stable')], db_index=True, help_text='The entity whose source text contained the mention.', max_length=20)),
                ('source_entity_id', models.PositiveIntegerField(db_index=True)),
                ('mention_text', models.CharField(help_text="The visible text of the link (e.g. 'Stampede Wrestling').", max_length=255)),
                ('wiki_link', models.CharField(db_index=True, help_text="The /wiki/X target (URL-decoded), e.g. 'Stampede_Wrestling'.", max_length=500)),
                ('context', models.CharField(choices=[('wrestler_about', 'Wrestler bio source'), ('promotion_about', 'Promotion bio source'), ('event_about', 'Event description')], default='wrestler_about', max_length=30)),
                ('resolved_entity_type', models.CharField(blank=True, choices=[('wrestler', 'Wrestler'), ('promotion', 'Promotion'), ('event', 'Event'), ('match', 'Match'), ('title', 'Title'), ('venue', 'Venue'), ('stable', 'Stable')], db_index=True, max_length=20, null=True)),
                ('resolved_entity_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_fetch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_mentions', to='wrestlebot.sourcefetch')),
            ],
            options={
                'ordering': ['-extracted_at'],
                'indexes': [models.Index(fields=['source_entity_type', 'source_entity_id'], name='wrestlebot__source__26cd29_idx'), models.Index(fields=['wiki_link'], name='wrestlebot__wiki_li_c810b1_idx'), models.Index(fields=['resolved_entity_type', 'resolved_entity_id'], name='wrestlebot__resolve_8e0763_idx')],
                'unique_together': {('source_fetch', 'wiki_link')},
            },
        ),
    ]
