# Generated by Django 5.2.14 on 2026-05-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestlebot', '0005_alter_sourcefetch_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitymention',
            name='resolved_entity_type',
            field=models.CharField(blank=True, choices=[('wrestler', 'Wrestler'), ('promotion', 'Promotion'), ('event', 'Event'), ('match', 'Match'), ('title', 'Title'), ('venue', 'Venue'), ('stable', 'Stable'), ('book', 'Book'), ('video_game', 'Video Game'), ('podcast', 'Podcast')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entitymention',
            name='source_entity_type',
            field=models.CharField(choices=[('wrestler', 'Wrestler'), ('promotion', 'Promotion'), ('event', 'Event'), ('match', 'Match'), ('title', 'Title'), ('venue', 'Venue'), ('stable', 'Stable'), ('book', 'Book'), ('video_game', 'Video Game'), ('podcast', 'Podcast')], db_index=True, help_text='The entity whose source text contained the mention.', max_length=20),
        ),
        migrations.AlterField(
            model_name='fieldprovenance',
            name='entity_type',
            field=models.CharField(choices=[('wrestler', 'Wrestler'), ('promotion', 'Promotion'), ('event', 'Event'), ('match', 'Match'), ('title', 'Title'), ('venue', 'Venue'), ('stable', 'Stable'), ('book', 'Book'), ('video_game', 'Video Game'), ('podcast', 'Podcast')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='generatedbio',
            name='entity_type',
            field=models.CharField(choices=[('wrestler', 'Wrestler'), ('promotion', 'Promotion'), ('event', 'Event'), ('match', 'Match'), ('title', 'Title'), ('venue', 'Venue'), ('stable', 'Stable'), ('book', 'Book'), ('video_game', 'Video Game'), ('podcast', 'Podcast')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sourcefetch',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('wrestler', 'Wrestler'), ('promotion', 'Promotion'), ('event', 'Event'), ('match', 'Match'), ('title', 'Title'), ('venue', 'Venue'), ('stable', 'Stable'), ('book', 'Book'), ('video_game', 'Video Game'), ('podcast', 'Podcast')], db_index=True, max_length=20, null=True),
        ),
    ]
