# Generated by Django 5.2.14 on 2026-05-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestlebot', '0009_alter_entitymention_resolved_entity_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('guard', 'Accuracy guard'), ('extractor', 'Field extractor'), ('cleanup', 'Cleanup pass'), ('consistency', 'Consistency rule')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('times_evaluated', models.PositiveIntegerField(default=0)),
                ('times_fired', models.PositiveIntegerField(default=0, help_text='Rule produced a non-default result')),
                ('true_positives', models.PositiveIntegerField(default=0, help_text='Fired and the call was correct')),
                ('false_positives', models.PositiveIntegerField(default=0, help_text='Fired but the call was wrong')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='False = Earl disabled this rule (Earl can re-enable)')),
                ('auto_disable_threshold', models.PositiveIntegerField(default=10, help_text='Earl auto-disables a rule that has >=N false positives unless overridden')),
                ('last_evaluated', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='', help_text="Earl's free-text notes about this rule")),
            ],
            options={
                'ordering': ['rule_id'],
            },
        ),
        migrations.CreateModel(
            name='RuleSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_rule_id', models.CharField(blank=True, default='', help_text="Existing rule to modify, or '' for a new rule", max_length=100)),
                ('kind', models.CharField(blank=True, default='', help_text='guard | extractor | cleanup | consistency', max_length=20)),
                ('description', models.TextField()),
                ('rationale', models.TextField(blank=True, default='', help_text='Why Earl thinks this change is needed (with sample observations)')),
                ('sample_observations', models.JSONField(blank=True, default=list, help_text='EntityIDs / values that motivated the suggestion')),
                ('status', models.CharField(choices=[('pending', 'Pending human review'), ('accepted', 'Accepted (applied or queued for apply)'), ('rejected', 'Rejected — kept current rule'), ('applied', 'Applied automatically')], db_index=True, default='pending', max_length=20)),
                ('proposed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-proposed_at'],
            },
        ),
        migrations.CreateModel(
            name='EarlObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(db_index=True, help_text="e.g. 'attendance_too_high', 'trained_by_prose_fragment'", max_length=100)),
                ('severity', models.CharField(db_index=True, help_text='warning | error', max_length=20)),
                ('entity_type', models.CharField(db_index=True, max_length=20)),
                ('entity_id', models.PositiveIntegerField(db_index=True)),
                ('entity_name', models.CharField(blank=True, default='', max_length=255)),
                ('field_name', models.CharField(blank=True, default='', max_length=100)),
                ('stored_value', models.TextField(blank=True, default='')),
                ('issue_description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open — not yet investigated'), ('investigating', 'Earl looking at it'), ('fixed', 'Resolved (either auto-fix applied or human edited)'), ('dismissed', "Earl decided it's a false positive"), ('escalated', 'Needs human review')], db_index=True, default='open', max_length=20)),
                ('auto_fix_applied', models.BooleanField(default=False)),
                ('auto_fix_notes', models.TextField(blank=True, default='')),
                ('first_seen', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('times_seen', models.PositiveIntegerField(default=1, help_text='Increments each audit that sees this same issue')),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['rule_id', 'status'], name='wrestlebot__rule_id_64b5d4_idx'), models.Index(fields=['entity_type', 'entity_id', 'rule_id'], name='wrestlebot__entity__082b0b_idx')],
                'unique_together': {('rule_id', 'entity_type', 'entity_id', 'field_name')},
            },
        ),
    ]
