# Generated by Django 5.2.14 on 2026-05-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestlebot', '0013_fieldprovenance_snippet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitymention',
            name='resolved_entity_type',
            field=models.CharField(blank=True, choices=[('wrestler', 'Wrestler'), ('promotion', 'Promotion'), ('event', 'Event'), ('match', 'Match'), ('title', 'Title'), ('venue', 'Venue'), ('stable', 'Stable'), ('book', 'Book'), ('video_game', 'Video Game'), ('podcast', 'Podcast'), ('action_figure', 'Action Figure'), ('theme_song', 'Theme Song'), ('tv_show', 'TV Show'), ('special', 'Documentary/Special'), ('training_school', 'Training School'), ('external_ranking', 'External Ranking')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entitymention',
            name='source_entity_type',
            field=models.CharField(choices=[('wrestler', 'Wrestler'), ('promotion', 'Promotion'), ('event', 'Event'), ('match', 'Match'), ('title', 'Title'), ('venue', 'Venue'), ('stable', 'Stable'), ('book', 'Book'), ('video_game', 'Video Game'), ('podcast', 'Podcast'), ('action_figure', 'Action Figure'), ('theme_song', 'Theme Song'), ('tv_show', 'TV Show'), ('special', 'Documentary/Special'), ('training_school', 'Training School'), ('external_ranking', 'External Ranking')], db_index=True, help_text='The entity whose source text contained the mention.', max_length=20),
        ),
        migrations.AlterField(
            model_name='fieldprovenance',
            name='entity_type',
            field=models.CharField(choices=[('wrestler', 'Wrestler'), ('promotion', 'Promotion'), ('event', 'Event'), ('match', 'Match'), ('title', 'Title'), ('venue', 'Venue'), ('stable', 'Stable'), ('book', 'Book'), ('video_game', 'Video Game'), ('podcast', 'Podcast'), ('action_figure', 'Action Figure'), ('theme_song', 'Theme Song'), ('tv_show', 'TV Show'), ('special', 'Documentary/Special'), ('training_school', 'Training School'), ('external_ranking', 'External Ranking')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='generatedbio',
            name='entity_type',
            field=models.CharField(choices=[('wrestler', 'Wrestler'), ('promotion', 'Promotion'), ('event', 'Event'), ('match', 'Match'), ('title', 'Title'), ('venue', 'Venue'), ('stable', 'Stable'), ('book', 'Book'), ('video_game', 'Video Game'), ('podcast', 'Podcast'), ('action_figure', 'Action Figure'), ('theme_song', 'Theme Song'), ('tv_show', 'TV Show'), ('special', 'Documentary/Special'), ('training_school', 'Training School'), ('external_ranking', 'External Ranking')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sourcefetch',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('wrestler', 'Wrestler'), ('promotion', 'Promotion'), ('event', 'Event'), ('match', 'Match'), ('title', 'Title'), ('venue', 'Venue'), ('stable', 'Stable'), ('book', 'Book'), ('video_game', 'Video Game'), ('podcast', 'Podcast'), ('action_figure', 'Action Figure'), ('theme_song', 'Theme Song'), ('tv_show', 'TV Show'), ('special', 'Documentary/Special'), ('training_school', 'Training School'), ('external_ranking', 'External Ranking')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sourcefetch',
            name='source',
            field=models.CharField(choices=[('wikipedia', 'Wikipedia'), ('wikidata', 'Wikidata'), ('cagematch', 'Cagematch'), ('profightdb', 'ProFightDB'), ('profightdb_pwi_mirror', "ProFightDB's PWI ranking mirror"), ('tmdb', 'TMDB'), ('wikimedia_commons', 'Wikimedia Commons'), ('openlibrary', 'Open Library')], db_index=True, max_length=50),
        ),
    ]
