# Generated by Django 5.2.14 on 2026-05-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestlebot', '0015_alter_agentsession_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefetch',
            name='extraction_outcome',
            field=models.CharField(blank=True, choices=[('', 'Not yet processed'), ('succeeded', 'Extracted and persisted'), ('no_fields', 'Extractor returned no fields (disambig / no infobox / unparseable)'), ('persist_refused', 'Persister refused (e.g., empty canonical name, unresolved FK)'), ('no_handler', 'No extractor or persister registered for entity_type')], db_index=True, default='', help_text="What the extract pipeline did with this fetch. Empty = not yet processed. Set together with used_at so failures don't re-queue.", max_length=30),
        ),
    ]
