# Generated by Django 5.1.14 on 2025-12-01 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=50, null=True)),
                ('nicknames', models.CharField(blank=True, max_length=255, null=True)),
                ('founded_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('closed_year', models.IntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='owdbapp_pro_name_0eae26_idx'), models.Index(fields=['abbreviation'], name='owdbapp_pro_abbrevi_44a3d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('debut_year', models.IntegerField(blank=True, null=True)),
                ('retirement_year', models.IntegerField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='owdbapp.promotion')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='owdbapp_ven_name_320ec4_idx'), models.Index(fields=['location'], name='owdbapp_ven_locatio_f7acf8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('attendance', models.IntegerField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='owdbapp.promotion')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='owdbapp.venue')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('release_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('systems', models.CharField(blank=True, help_text='e.g., PS5, Xbox, PC', max_length=255, null=True)),
                ('developer', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('promotions', models.ManyToManyField(blank=True, related_name='video_games', to='owdbapp.promotion')),
            ],
            options={
                'ordering': ['-release_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Wrestler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('real_name', models.CharField(blank=True, max_length=255, null=True)),
                ('aliases', models.TextField(blank=True, help_text='Comma-separated list of aliases', null=True)),
                ('debut_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('retirement_year', models.IntegerField(blank=True, null=True)),
                ('hometown', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('finishers', models.TextField(blank=True, help_text='Comma-separated list of finishing moves', null=True)),
                ('about', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'wrestlers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='owdbapp_wre_name_4e049a_idx'), models.Index(fields=['debut_year'], name='owdbapp_wre_debut_y_ec7075_idx'), models.Index(fields=['nationality'], name='owdbapp_wre_nationa_8a6ce0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('documentary', 'Documentary'), ('movie', 'Movie'), ('tv_special', 'TV Special'), ('series', 'Series'), ('other', 'Other')], default='other', max_length=50)),
                ('about', models.TextField(blank=True, null=True)),
                ('related_wrestlers', models.ManyToManyField(blank=True, related_name='specials', to='owdbapp.wrestler')),
            ],
            options={
                'ordering': ['-release_year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('hosts', models.TextField(blank=True, help_text='Comma-separated list of hosts', null=True)),
                ('launch_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('related_wrestlers', models.ManyToManyField(blank=True, related_name='podcasts', to='owdbapp.wrestler')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_text', models.TextField(help_text="Description like 'The Rock vs Stone Cold'")),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('match_type', models.CharField(blank=True, max_length=255, null=True)),
                ('match_order', models.PositiveIntegerField(default=0, help_text='Order on the card')),
                ('about', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='owdbapp.event')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_matches', to='owdbapp.title')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='owdbapp.wrestler')),
                ('wrestlers', models.ManyToManyField(related_name='matches', to='owdbapp.wrestler')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['event', 'match_order'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('author', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('related_wrestlers', models.ManyToManyField(blank=True, related_name='books', to='owdbapp.wrestler')),
            ],
            options={
                'ordering': ['-publication_year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional name for this key', max_length=100, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('requests_today', models.IntegerField(default=0)),
                ('requests_total', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('last_reset', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'indexes': [models.Index(fields=['key'], name='owdbapp_api_key_c57e64_idx'), models.Index(fields=['user'], name='owdbapp_api_user_id_ac6e0b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['name'], name='owdbapp_tit_name_c4156b_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['promotion'], name='owdbapp_tit_promoti_b0b051_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['name'], name='owdbapp_eve_name_ab6b11_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date'], name='owdbapp_eve_date_e71316_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['promotion', 'date'], name='owdbapp_eve_promoti_0574f6_idx'),
        ),
        migrations.AddIndex(
            model_name='videogame',
            index=models.Index(fields=['name'], name='owdbapp_vid_name_918fa7_idx'),
        ),
        migrations.AddIndex(
            model_name='videogame',
            index=models.Index(fields=['release_year'], name='owdbapp_vid_release_c8e742_idx'),
        ),
        migrations.AddIndex(
            model_name='special',
            index=models.Index(fields=['title'], name='owdbapp_spe_title_aa177c_idx'),
        ),
        migrations.AddIndex(
            model_name='special',
            index=models.Index(fields=['type'], name='owdbapp_spe_type_44baf3_idx'),
        ),
        migrations.AddIndex(
            model_name='podcast',
            index=models.Index(fields=['name'], name='owdbapp_pod_name_8a2b40_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['event'], name='owdbapp_mat_event_i_000b69_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['match_type'], name='owdbapp_mat_match_t_1b066e_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='owdbapp_boo_title_e6bdf9_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author'], name='owdbapp_boo_author_7faf61_idx'),
        ),
    ]
