# Generated by Django 5.1.14 on 2025-12-12 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owdbapp', '0002_wrestlebot_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_credit',
            field=models.CharField(blank=True, default='', help_text='Attribution text for license compliance', max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='image_fetched_at',
            field=models.DateTimeField(blank=True, help_text='When the image was fetched', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image_license',
            field=models.CharField(blank=True, choices=[('cc0', 'CC0 - Public Domain'), ('cc-by', 'CC BY'), ('cc-by-sa', 'CC BY-SA'), ('pd', 'Public Domain')], default='', help_text='Creative Commons license type', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='image_source_url',
            field=models.URLField(blank=True, help_text='URL to the original source page (e.g., Wikimedia Commons)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to the image file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='image_credit',
            field=models.CharField(blank=True, default='', help_text='Attribution text for license compliance', max_length=500),
        ),
        migrations.AddField(
            model_name='promotion',
            name='image_fetched_at',
            field=models.DateTimeField(blank=True, help_text='When the image was fetched', null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='image_license',
            field=models.CharField(blank=True, choices=[('cc0', 'CC0 - Public Domain'), ('cc-by', 'CC BY'), ('cc-by-sa', 'CC BY-SA'), ('pd', 'Public Domain')], default='', help_text='Creative Commons license type', max_length=20),
        ),
        migrations.AddField(
            model_name='promotion',
            name='image_source_url',
            field=models.URLField(blank=True, help_text='URL to the original source page (e.g., Wikimedia Commons)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to the image file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='image_credit',
            field=models.CharField(blank=True, default='', help_text='Attribution text for license compliance', max_length=500),
        ),
        migrations.AddField(
            model_name='title',
            name='image_fetched_at',
            field=models.DateTimeField(blank=True, help_text='When the image was fetched', null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='image_license',
            field=models.CharField(blank=True, choices=[('cc0', 'CC0 - Public Domain'), ('cc-by', 'CC BY'), ('cc-by-sa', 'CC BY-SA'), ('pd', 'Public Domain')], default='', help_text='Creative Commons license type', max_length=20),
        ),
        migrations.AddField(
            model_name='title',
            name='image_source_url',
            field=models.URLField(blank=True, help_text='URL to the original source page (e.g., Wikimedia Commons)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to the image file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='image_credit',
            field=models.CharField(blank=True, default='', help_text='Attribution text for license compliance', max_length=500),
        ),
        migrations.AddField(
            model_name='venue',
            name='image_fetched_at',
            field=models.DateTimeField(blank=True, help_text='When the image was fetched', null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='image_license',
            field=models.CharField(blank=True, choices=[('cc0', 'CC0 - Public Domain'), ('cc-by', 'CC BY'), ('cc-by-sa', 'CC BY-SA'), ('pd', 'Public Domain')], default='', help_text='Creative Commons license type', max_length=20),
        ),
        migrations.AddField(
            model_name='venue',
            name='image_source_url',
            field=models.URLField(blank=True, help_text='URL to the original source page (e.g., Wikimedia Commons)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to the image file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='wrestler',
            name='image_credit',
            field=models.CharField(blank=True, default='', help_text='Attribution text for license compliance', max_length=500),
        ),
        migrations.AddField(
            model_name='wrestler',
            name='image_fetched_at',
            field=models.DateTimeField(blank=True, help_text='When the image was fetched', null=True),
        ),
        migrations.AddField(
            model_name='wrestler',
            name='image_license',
            field=models.CharField(blank=True, choices=[('cc0', 'CC0 - Public Domain'), ('cc-by', 'CC BY'), ('cc-by-sa', 'CC BY-SA'), ('pd', 'Public Domain')], default='', help_text='Creative Commons license type', max_length=20),
        ),
        migrations.AddField(
            model_name='wrestler',
            name='image_source_url',
            field=models.URLField(blank=True, help_text='URL to the original source page (e.g., Wikimedia Commons)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='wrestler',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to the image file', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('can_contribute', models.BooleanField(default=False, help_text='Can add/edit content after email verification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification Token',
                'verbose_name_plural': 'Email Verification Tokens',
                'indexes': [models.Index(fields=['token'], name='owdbapp_ema_token_6166e5_idx'), models.Index(fields=['user'], name='owdbapp_ema_user_id_cc6896_idx')],
            },
        ),
    ]
