# Generated by Django 5.1.14 on 2025-12-19 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owdbapp', '0005_boost_wrestlebot_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='cagematch_url',
            field=models.URLField(blank=True, help_text='Cagematch.net database URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='profightdb_url',
            field=models.URLField(blank=True, help_text='ProFightDB promotion URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='wrestler',
            name='cagematch_url',
            field=models.URLField(blank=True, help_text='Cagematch.net profile URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='wrestler',
            name='profightdb_url',
            field=models.URLField(blank=True, help_text='ProFightDB profile URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='wrestlebotlog',
            name='entity_type',
            field=models.CharField(choices=[('wrestler', 'Wrestler'), ('promotion', 'Promotion'), ('event', 'Event'), ('match', 'Match'), ('title', 'Title'), ('venue', 'Venue'), ('stable', 'Stable'), ('videogame', 'Video Game'), ('podcast', 'Podcast'), ('book', 'Book'), ('special', 'Special')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='wikipedia_url',
            field=models.URLField(blank=True, help_text='Wikipedia article URL', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Stable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, help_text='URL to the image file', max_length=500, null=True)),
                ('image_source_url', models.URLField(blank=True, help_text='URL to the original source page (e.g., Wikimedia Commons)', max_length=500, null=True)),
                ('image_license', models.CharField(blank=True, choices=[('cc0', 'CC0 - Public Domain'), ('cc-by', 'CC BY'), ('cc-by-sa', 'CC BY-SA'), ('pd', 'Public Domain')], default='', help_text='Creative Commons license type', max_length=20)),
                ('image_credit', models.CharField(blank=True, default='', help_text='Attribution text for license compliance', max_length=500)),
                ('image_fetched_at', models.DateTimeField(blank=True, help_text='When the image was fetched', null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('formed_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('disbanded_year', models.IntegerField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('manager', models.CharField(blank=True, help_text='Non-wrestler manager if applicable', max_length=255, null=True)),
                ('wikipedia_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cagematch_url', models.URLField(blank=True, max_length=500, null=True)),
                ('profightdb_url', models.URLField(blank=True, max_length=500, null=True)),
                ('last_enriched', models.DateTimeField(blank=True, null=True)),
                ('leaders', models.ManyToManyField(blank=True, help_text='Leaders/founders of the stable', related_name='stables_led', to='owdbapp.wrestler')),
                ('members', models.ManyToManyField(blank=True, help_text='Current and former members', related_name='stables', to='owdbapp.wrestler')),
                ('promotion', models.ForeignKey(blank=True, help_text='Primary promotion (may appear in multiple)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stables', to='owdbapp.promotion')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='owdbapp_sta_name_9c0cef_idx'), models.Index(fields=['formed_year'], name='owdbapp_sta_formed__2f10d2_idx')],
            },
        ),
    ]
