# Generated by Django 5.2.9 on 2025-12-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owdbapp', '0006_add_stable_and_multisource'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_original_url',
            field=models.URLField(blank=True, help_text='Original image URL before caching to R2', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='image_original_url',
            field=models.URLField(blank=True, help_text='Original image URL before caching to R2', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='stable',
            name='image_original_url',
            field=models.URLField(blank=True, help_text='Original image URL before caching to R2', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='image_original_url',
            field=models.URLField(blank=True, help_text='Original image URL before caching to R2', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='image_original_url',
            field=models.URLField(blank=True, help_text='Original image URL before caching to R2', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='wrestler',
            name='image_original_url',
            field=models.URLField(blank=True, help_text='Original image URL before caching to R2', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to the cached image on R2 CDN', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to the cached image on R2 CDN', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stable',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to the cached image on R2 CDN', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to the cached image on R2 CDN', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to the cached image on R2 CDN', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to the cached image on R2 CDN', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='ImageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('wrestler', 'Wrestler'), ('promotion', 'Promotion'), ('venue', 'Venue'), ('event', 'Event'), ('title', 'Title'), ('stable', 'Stable')], db_index=True, max_length=20)),
                ('entity_id', models.PositiveIntegerField(db_index=True)),
                ('image_url', models.URLField(help_text='URL to the cached image on R2 CDN', max_length=500)),
                ('image_source_url', models.URLField(blank=True, help_text='URL to the original source page', max_length=500, null=True)),
                ('image_original_url', models.URLField(blank=True, help_text='Original image URL before caching', max_length=500, null=True)),
                ('image_license', models.CharField(blank=True, choices=[('cc0', 'CC0 - Public Domain'), ('cc-by', 'CC BY'), ('cc-by-sa', 'CC BY-SA'), ('pd', 'Public Domain')], default='', max_length=20)),
                ('image_credit', models.CharField(blank=True, default='', max_length=500)),
                ('active_from', models.DateTimeField(help_text='When this image became active')),
                ('active_until', models.DateTimeField(auto_now_add=True, help_text='When this image was replaced')),
                ('replacement_reason', models.CharField(blank=True, default='', help_text="Why image was replaced (e.g., 'better_image_found', 'scheduled_refresh')", max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Image histories',
                'ordering': ['-active_until'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='owdbapp_ima_entity__001524_idx'), models.Index(fields=['entity_type', 'entity_id', '-active_until'], name='owdbapp_ima_entity__228940_idx')],
            },
        ),
    ]
