# Generated by Django 5.1.14 on 2025-12-19 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owdbapp', '0007_add_image_history_and_original_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hot100Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.IntegerField(db_index=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Hot 100 Ranking',
                'verbose_name_plural': 'Hot 100 Rankings',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Hot100Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.IntegerField(db_index=True)),
                ('total_score', models.FloatField()),
                ('match_count_score', models.FloatField(default=0)),
                ('match_importance_score', models.FloatField(default=0)),
                ('title_activity_score', models.FloatField(default=0)),
                ('opponent_quality_score', models.FloatField(default=0)),
                ('news_mention_score', models.FloatField(default=0)),
                ('social_engagement_score', models.FloatField(default=0)),
                ('website_views_score', models.FloatField(default=0)),
                ('previous_rank', models.IntegerField(blank=True, null=True)),
                ('rank_change', models.IntegerField(default=0)),
                ('wrestler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot100_entries', to='owdbapp.wrestler')),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='owdbapp.hot100ranking')),
            ],
            options={
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['ranking', 'rank'], name='owdbapp_hot_ranking_c617be_idx'), models.Index(fields=['wrestler'], name='owdbapp_hot_wrestle_ea3eb3_idx')],
                'unique_together': {('ranking', 'wrestler')},
            },
        ),
    ]
