# Generated by Django 5.1.14 on 2025-12-20 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owdbapp', '0008_add_hot100_rankings'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='apple_podcasts_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='host_wrestlers',
            field=models.ManyToManyField(blank=True, help_text='Wrestler hosts of this podcast', related_name='podcasts_hosted', to='owdbapp.wrestler'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='last_rss_fetch',
            field=models.DateTimeField(blank=True, help_text='When episodes were last fetched from RSS', null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='rss_feed_url',
            field=models.URLField(blank=True, help_text='RSS feed URL for automatic episode import', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='spotify_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('episode_number', models.IntegerField(blank=True, null=True)),
                ('season_number', models.IntegerField(blank=True, null=True)),
                ('published_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('audio_url', models.URLField(blank=True, max_length=500, null=True)),
                ('episode_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('guid', models.CharField(blank=True, help_text='Unique ID from RSS feed for deduplication', max_length=500, null=True, unique=True)),
                ('guests', models.ManyToManyField(blank=True, help_text='Wrestlers who appeared as guests on this episode', related_name='podcast_appearances', to='owdbapp.wrestler')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='owdbapp.podcast')),
            ],
            options={
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['podcast', '-published_date'], name='owdbapp_pod_podcast_634268_idx'), models.Index(fields=['guid'], name='owdbapp_pod_guid_785413_idx')],
            },
        ),
        migrations.CreateModel(
            name='WrestlerPromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, help_text='Null if currently active', null=True)),
                ('notes', models.CharField(blank=True, help_text="e.g., 'As Stone Cold', 'NXT only'", max_length=255, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrestler_history', to='owdbapp.promotion')),
                ('wrestler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_history', to='owdbapp.wrestler')),
            ],
            options={
                'verbose_name_plural': 'Wrestler promotion histories',
                'ordering': ['-start_year'],
                'indexes': [models.Index(fields=['wrestler', '-start_year'], name='owdbapp_wre_wrestle_dfa434_idx'), models.Index(fields=['promotion', '-start_year'], name='owdbapp_wre_promoti_667e85_idx')],
                'unique_together': {('wrestler', 'promotion', 'start_year')},
            },
        ),
    ]
