# Generated by Django 5.1.14 on 2025-12-31 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owdbapp', '0013_add_wrestler_death_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, help_text='URL to the cached image on R2 CDN', max_length=500, null=True)),
                ('image_source_url', models.URLField(blank=True, help_text='URL to the original source page (e.g., Wikimedia Commons)', max_length=500, null=True)),
                ('image_original_url', models.URLField(blank=True, help_text='Original image URL before caching to R2', max_length=500, null=True)),
                ('image_license', models.CharField(blank=True, choices=[('cc0', 'CC0 - Public Domain'), ('cc-by', 'CC BY'), ('cc-by-sa', 'CC BY-SA'), ('pd', 'Public Domain')], default='', help_text='Creative Commons license type', max_length=20)),
                ('image_credit', models.CharField(blank=True, default='', help_text='Attribution text for license compliance', max_length=500)),
                ('image_fetched_at', models.DateTimeField(blank=True, help_text='When the image was fetched', null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('show_type', models.CharField(choices=[('weekly', 'Weekly TV Show'), ('ppv', 'Pay-Per-View Series'), ('special', 'Special Event Series'), ('online', 'Online/Streaming Show')], default='weekly', max_length=50)),
                ('network', models.CharField(blank=True, help_text='Current network (e.g., Netflix, USA Network, TBS)', max_length=100, null=True)),
                ('air_day', models.CharField(blank=True, help_text='Day of week (e.g., Monday, Wednesday)', max_length=20, null=True)),
                ('premiere_date', models.DateField(blank=True, null=True)),
                ('finale_date', models.DateField(blank=True, help_text='NULL = still running', null=True)),
                ('tmdb_id', models.IntegerField(blank=True, help_text='The Movie Database TV show ID', null=True, unique=True)),
                ('cagematch_id', models.IntegerField(blank=True, help_text='Cagematch event series ID', null=True)),
                ('wikipedia_url', models.URLField(blank=True, max_length=500, null=True)),
                ('about', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'TV Show',
                'verbose_name_plural': 'TV Shows',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='wrestlebotactivity',
            new_name='owdbapp_wre_action__e6fdcd_idx',
            old_name='owdbapp_wre_action__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='wrestlebotactivity',
            new_name='owdbapp_wre_entity__d2b355_idx',
            old_name='owdbapp_wre_entity__d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='wrestlebotactivity',
            new_name='owdbapp_wre_source_b45889_idx',
            old_name='owdbapp_wre_source__g7h8i9_idx',
        ),
        migrations.RenameIndex(
            model_name='wrestlebotactivity',
            new_name='owdbapp_wre_ai_assi_fc2db8_idx',
            old_name='owdbapp_wre_ai_assi_j0k1l2_idx',
        ),
        migrations.AddField(
            model_name='event',
            name='cagematch_event_id',
            field=models.IntegerField(blank=True, help_text='Cagematch event ID', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='episode_number',
            field=models.IntegerField(blank=True, help_text='Episode number within the show', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('tv_episode', 'TV Episode'), ('ppv', 'Pay-Per-View'), ('house_show', 'House Show'), ('special', 'Special Event'), ('other', 'Other')], db_index=True, default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='last_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='season_number',
            field=models.IntegerField(blank=True, help_text='Season number (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tmdb_episode_id',
            field=models.IntegerField(blank=True, help_text='TMDB episode ID for TV episodes', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='verified',
            field=models.BooleanField(default=False, help_text='Data verified against external source'),
        ),
        migrations.AddField(
            model_name='event',
            name='verified_source',
            field=models.CharField(blank=True, help_text='Source used for verification', max_length=50, null=True),
        ),
        # NOTE: podcastepisode.discussed_events, discussed_matches, and videogame.wrestlers
        # already exist in the database from a previous migration, so we skip creating them here.
        migrations.AddField(
            model_name='tvshow',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tv_shows', to='owdbapp.promotion'),
        ),
        migrations.AddField(
            model_name='event',
            name='tv_show',
            field=models.ForeignKey(blank=True, help_text='TV show this episode belongs to (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes', to='owdbapp.tvshow'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['tv_show', 'episode_number'], name='owdbapp_eve_tv_show_efd88a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='owdbapp_eve_event_t_23e599_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['verified'], name='owdbapp_eve_verifie_f7818d_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['tv_show', 'date'], name='owdbapp_eve_tv_show_54f4c3_idx'),
        ),
        migrations.AddIndex(
            model_name='tvshow',
            index=models.Index(fields=['promotion', 'show_type'], name='owdbapp_tvs_promoti_c061d8_idx'),
        ),
        migrations.AddIndex(
            model_name='tvshow',
            index=models.Index(fields=['tmdb_id'], name='owdbapp_tvs_tmdb_id_bbed8d_idx'),
        ),
        migrations.AddIndex(
            model_name='tvshow',
            index=models.Index(fields=['show_type'], name='owdbapp_tvs_show_ty_1c329c_idx'),
        ),
    ]
