# Generated by Django 5.2.14 on 2026-05-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owdbapp", "0019_trainerrelationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="last_enriched",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="last_verified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="opened_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="verification_source",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="verified",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="venue",
            name="wikipedia_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name="venue",
            index=models.Index(fields=["verified"], name="owdbapp_ven_verifie_89576f_idx"),
        ),
    ]
