# Generated by Django 5.2.14 on 2026-05-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owdbapp", "0023_stable_last_verified_stable_verification_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="special",
            name="director",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="special",
            name="last_enriched",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="special",
            name="last_verified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="special",
            name="verification_source",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="special",
            name="verified",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="special",
            name="wikipedia_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="tvshow",
            name="last_enriched",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tvshow",
            name="last_verified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tvshow",
            name="verification_source",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="tvshow",
            name="verified",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="special",
            index=models.Index(fields=["verified"], name="owdbapp_spe_verifie_306e19_idx"),
        ),
        migrations.AddIndex(
            model_name="tvshow",
            index=models.Index(fields=["verified"], name="owdbapp_tvs_verifie_8e5cf1_idx"),
        ),
    ]
