# Generated by Django 5.2.14 on 2026-05-27 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owdbapp", "0024_special_director_special_last_enriched_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wrestler",
            name="roles",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="wrestler",
                help_text="Comma-separated roles (wrestler, commentator, referee, etc.)",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="TrainingSchool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="City / state / country", max_length=255, null=True
                    ),
                ),
                ("founded_year", models.IntegerField(blank=True, db_index=True, null=True)),
                ("closed_year", models.IntegerField(blank=True, null=True)),
                ("founder", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "head_trainer",
                    models.CharField(
                        blank=True,
                        help_text="Current / most-recent head trainer (text — may be a Wrestler)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("about", models.TextField(blank=True, null=True)),
                ("wikipedia_url", models.URLField(blank=True, max_length=500, null=True)),
                ("last_enriched", models.DateTimeField(blank=True, null=True)),
                ("verified", models.BooleanField(db_index=True, default=False)),
                ("verification_source", models.CharField(blank=True, max_length=50, null=True)),
                ("last_verified", models.DateTimeField(blank=True, null=True)),
                (
                    "notable_trainees",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Wrestlers known to have trained here",
                        related_name="training_schools_attended",
                        to="owdbapp.wrestler",
                    ),
                ),
                (
                    "parent_promotion",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent promotion if any (e.g., WWE Performance Center -> WWE)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_schools",
                        to="owdbapp.promotion",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="owdbapp_tra_name_931dd8_idx"),
                    models.Index(fields=["founded_year"], name="owdbapp_tra_founded_8e33ce_idx"),
                    models.Index(fields=["verified"], name="owdbapp_tra_verifie_c35cdc_idx"),
                ],
            },
        ),
    ]
