# Generated by Django 5.2.14 on 2026-05-27 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owdbapp", "0025_wrestler_roles_trainingschool"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "list_kind",
                    models.CharField(
                        choices=[
                            ("pwi_500", "PWI 500"),
                            ("pwi_female_50", "PWI Female 50"),
                            ("pwi_female_100", "PWI Female 100"),
                            ("pwi_female_150", "PWI Female 150"),
                            ("observer_match", "Wrestling Observer — Match of the Year"),
                            ("observer_wrestler", "Wrestling Observer — Wrestler of the Year"),
                            ("observer_feud", "Wrestling Observer — Feud of the Year"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("year", models.IntegerField(db_index=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Display title, e.g. 'PWI 500 (2023)'",
                        max_length=200,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Where this list was ingested from.",
                        max_length=500,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-year", "list_kind"],
            },
        ),
        migrations.CreateModel(
            name="ExternalRankingEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(db_index=True)),
                ("wrestler_name_as_published", models.CharField(db_index=True, max_length=200)),
                ("blurb", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["ranking", "position"],
            },
        ),
        migrations.CreateModel(
            name="MatchParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "side",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Team/faction index — 0 = first side, 1 = second, etc.",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("captain", "Captain"),
                            ("partner", "Partner"),
                            ("manager", "Manager / second"),
                            ("guest_referee", "Guest referee"),
                            ("special_enforcer", "Special enforcer"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("is_winner", models.BooleanField(db_index=True, default=False)),
                (
                    "entrance_order",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="For Royal Rumble / battle royal — entrance number.",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["match", "side", "id"],
            },
        ),
        migrations.CreateModel(
            name="UserRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("wrestler", "Wrestler"),
                            ("event", "Event"),
                            ("match", "Match"),
                            ("title", "Title"),
                            ("stable", "Stable"),
                            ("promotion", "Promotion"),
                            ("tv_show", "TV show"),
                            ("special", "Special / documentary"),
                            ("book", "Book"),
                            ("video_game", "Video game"),
                            ("podcast", "Podcast"),
                            ("theme_song", "Theme song"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("entity_id", models.PositiveIntegerField(db_index=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="1-10 integer rating. Null = no rating, only a favorite or review.",
                        null=True,
                    ),
                ),
                ("is_favorite", models.BooleanField(db_index=True, default=False)),
                ("review_text", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.AddField(
            model_name="match",
            name="cagematch_rating",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=2,
                help_text="Cagematch user rating, 0.00-10.00",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="cagematch_rating_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="How many users rated the match on Cagematch", null=True
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="duration_seconds",
            field=models.PositiveIntegerField(
                blank=True, help_text="Bell-to-bell match length", null=True
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="observer_stars",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Wrestling Observer (Meltzer) star rating, 0.00-5.00",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="outcome_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pinfall", "Pinfall"),
                    ("submission", "Submission"),
                    ("dq", "Disqualification"),
                    ("count_out", "Count-out"),
                    ("knockout", "Knockout"),
                    ("no_contest", "No contest"),
                    ("draw", "Draw / time limit"),
                    ("forfeit", "Forfeit"),
                    ("other", "Other / unknown"),
                ],
                db_index=True,
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="profightdb_match_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="ProFightDB match identifier for cross-reference",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="title_changed",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True iff a title changed hands in this match",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="winning_side",
            field=models.IntegerField(
                blank=True,
                help_text="Index of the winning side (matches MatchParticipant.side)",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["-cagematch_rating"], name="owdbapp_mat_cagemat_37b353_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["title_changed"], name="owdbapp_mat_title_c_20f8b2_idx"),
        ),
        migrations.AddIndex(
            model_name="externalranking",
            index=models.Index(
                fields=["list_kind", "-year"], name="owdbapp_ext_list_ki_f8999c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="externalranking",
            unique_together={("list_kind", "year")},
        ),
        migrations.AddField(
            model_name="externalrankingentry",
            name="ranking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="owdbapp.externalranking",
            ),
        ),
        migrations.AddField(
            model_name="externalrankingentry",
            name="wrestler",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="external_rankings",
                to="owdbapp.wrestler",
            ),
        ),
        migrations.AddField(
            model_name="matchparticipant",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participant_links",
                to="owdbapp.match",
            ),
        ),
        migrations.AddField(
            model_name="matchparticipant",
            name="wrestler",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_participations",
                to="owdbapp.wrestler",
            ),
        ),
        migrations.AddField(
            model_name="userrating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="externalrankingentry",
            index=models.Index(
                fields=["wrestler", "ranking"], name="owdbapp_ext_wrestle_30d594_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalrankingentry",
            index=models.Index(
                fields=["wrestler_name_as_published"], name="owdbapp_ext_wrestle_7dbe9b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="externalrankingentry",
            unique_together={("ranking", "position")},
        ),
        migrations.AddIndex(
            model_name="matchparticipant",
            index=models.Index(fields=["match", "side"], name="owdbapp_mat_match_i_7c3c0c_idx"),
        ),
        migrations.AddIndex(
            model_name="matchparticipant",
            index=models.Index(
                fields=["wrestler", "is_winner"], name="owdbapp_mat_wrestle_df5a77_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="matchparticipant",
            unique_together={("match", "wrestler")},
        ),
        migrations.AddIndex(
            model_name="userrating",
            index=models.Index(
                fields=["entity_type", "entity_id", "-rating"],
                name="owdbapp_use_entity__d4498d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userrating",
            index=models.Index(
                fields=["user", "is_favorite"], name="owdbapp_use_user_id_142aed_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userrating",
            unique_together={("user", "entity_type", "entity_id")},
        ),
    ]
