# Generated by Django 5.2.14 on 2026-05-27, edited 2026-05-27 to be DB-no-op.
#
# We renamed Event.verified_source → Event.verification_source at the
# Python level, but the new field carries `db_column="verified_source"`
# so the physical column name (and its data) is preserved. The naive
# auto-generated migration would `DROP COLUMN verified_source` then
# `ADD COLUMN verified_source` — losing every existing value.
#
# `SeparateDatabaseAndState` lets us update Django's internal model state
# without issuing any SQL. The data on disk is untouched; only the
# Python attribute name changes.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owdbapp', '0026_externalranking_externalrankingentry_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='event',
                    name='verified_source',
                ),
                migrations.AddField(
                    model_name='event',
                    name='verification_source',
                    field=models.CharField(
                        blank=True, db_column='verified_source',
                        help_text='Source used for verification',
                        max_length=50, null=True,
                    ),
                ),
            ],
        ),
    ]
