# Generated by Django 5.2.14 on 2026-05-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owdbapp", "0027_remove_event_verified_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="verification_state",
            field=models.CharField(
                choices=[
                    ("candidate", "Candidate (unconfirmed reference)"),
                    ("provisional", "Provisional (data without per-field provenance)"),
                    ("verified", "Verified (passes accuracy contract)"),
                    ("rejected", "Rejected (incorrect / duplicate / junk)"),
                ],
                db_index=True,
                default="candidate",
                help_text="Where this entity sits on the accuracy contract.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="verification_state",
            field=models.CharField(
                choices=[
                    ("candidate", "Candidate (unconfirmed reference)"),
                    ("provisional", "Provisional (data without per-field provenance)"),
                    ("verified", "Verified (passes accuracy contract)"),
                    ("rejected", "Rejected (incorrect / duplicate / junk)"),
                ],
                db_index=True,
                default="candidate",
                help_text="Where this entity sits on the accuracy contract.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="verification_state",
            field=models.CharField(
                choices=[
                    ("candidate", "Candidate (unconfirmed reference)"),
                    ("provisional", "Provisional (data without per-field provenance)"),
                    ("verified", "Verified (passes accuracy contract)"),
                    ("rejected", "Rejected (incorrect / duplicate / junk)"),
                ],
                db_index=True,
                default="candidate",
                help_text="Where this entity sits on the accuracy contract.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="stable",
            name="verification_state",
            field=models.CharField(
                choices=[
                    ("candidate", "Candidate (unconfirmed reference)"),
                    ("provisional", "Provisional (data without per-field provenance)"),
                    ("verified", "Verified (passes accuracy contract)"),
                    ("rejected", "Rejected (incorrect / duplicate / junk)"),
                ],
                db_index=True,
                default="candidate",
                help_text="Where this entity sits on the accuracy contract.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="title",
            name="verification_state",
            field=models.CharField(
                choices=[
                    ("candidate", "Candidate (unconfirmed reference)"),
                    ("provisional", "Provisional (data without per-field provenance)"),
                    ("verified", "Verified (passes accuracy contract)"),
                    ("rejected", "Rejected (incorrect / duplicate / junk)"),
                ],
                db_index=True,
                default="candidate",
                help_text="Where this entity sits on the accuracy contract.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tvshow",
            name="verification_state",
            field=models.CharField(
                choices=[
                    ("candidate", "Candidate (unconfirmed reference)"),
                    ("provisional", "Provisional (data without per-field provenance)"),
                    ("verified", "Verified (passes accuracy contract)"),
                    ("rejected", "Rejected (incorrect / duplicate / junk)"),
                ],
                db_index=True,
                default="candidate",
                help_text="Where this entity sits on the accuracy contract.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="verification_state",
            field=models.CharField(
                choices=[
                    ("candidate", "Candidate (unconfirmed reference)"),
                    ("provisional", "Provisional (data without per-field provenance)"),
                    ("verified", "Verified (passes accuracy contract)"),
                    ("rejected", "Rejected (incorrect / duplicate / junk)"),
                ],
                db_index=True,
                default="candidate",
                help_text="Where this entity sits on the accuracy contract.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="wrestler",
            name="verification_state",
            field=models.CharField(
                choices=[
                    ("candidate", "Candidate (unconfirmed reference)"),
                    ("provisional", "Provisional (data without per-field provenance)"),
                    ("verified", "Verified (passes accuracy contract)"),
                    ("rejected", "Rejected (incorrect / duplicate / junk)"),
                ],
                db_index=True,
                default="candidate",
                help_text="Where this entity sits on the accuracy contract.",
                max_length=20,
            ),
        ),
    ]
