# Generated by Django 6.0.8 on 2026-09-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owdbapp", "0030_book_promotions_special_promotions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrating",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("wrestler", "Wrestler"),
                    ("event", "Event"),
                    ("match", "Match"),
                    ("title", "Title"),
                    ("stable", "Stable"),
                    ("promotion", "Promotion"),
                    ("venue", "Venue"),
                    ("tv_show", "TV show"),
                    ("special", "Special / documentary"),
                    ("book", "Book"),
                    ("video_game", "Video game"),
                    ("podcast", "Podcast"),
                    ("theme_song", "Theme song"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
